### ISSUE TITLE
Unable to edit Closed quiz metadata

### ISSUE THREAD

**Issue by scottpeterson** [gryphonshafer/pnwquizzing#14]
On the Stats page, Closed quizzes, I can click on any quiz name, but once there, cannot edit any metadata. 

Use Case, while quizzes are occurring, edit Quiz Room Numbers and Quiz Names to be consistent. (e.g. get rid of Room = 9)

**Comment by gryphonshafer** [comment]
Turns out, this isn't a PNWQuizzing bug. It's a CBQZ bug. So I'm moving this ticket there.
